name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Unit Testing
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: tests:test --build-cache --daemon --parallel --stacktrace

    - name: Build with Gradle
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: desktop:dist --build-cache --daemon --parallel --stacktrace

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: SpiceTraders
        path: desktop/build/libs/desktop-1.0.jar
        retention-days: 3
